### ISSUE TITLE
Not sure how to save patch to fs

### ISSUE THREAD

**Issue by sporchia** [althonos/flips.rs#1]
First off, I'm very new to Rust, so I'm sure I could just be doing things wrong. Also this is really cool that this package exists.

I'm having trouble figuring out how to output a bps patch to disk. This is what I have so far:

```rust
let dest = std::fs::read("final.sfc").unwrap();
let src = std::fs::read("input.sfc").unwrap();
let patch = flips::BpsLinearBuilder::new()
    .source(src)
    .target(dest)
    .build()
    .expect("could not create patch");

//println!("{:?}", patch);

// this does not work :(
//std::fs::write("out.bps", patch).unwrap();
```

any help would be super appreciated.

**Comment by althonos** [comment]
Hi @sporchia ! Thanks for using this package, I was really not sure I would be of any use so it's nice to see people trying it :smiley: 

After checking, I realise that I forgot to implement `AsRef<[u8]>` for patches like I did for input and output types, so I'll patch that ASAP, but once it's done you should be able to do what you described.

**Comment by althonos** [comment]
@sporchia : `v0.2.1` is out, and you should be able to use `std::fs::write` now.

**Comment by sporchia** [comment]
perfect! thank you!
